LastFood = input("Warden : Anything you want to eat before the sentence ?\n")
print("Prisoner : I want " +  LastFood )
LastThing = input("Warden : Anything you want to do before the sentence ?\n")
print("Prisoner : I want to " +  LastThing )
LastWords = input("Warden : Any lastwords?\n")
print("Prisoner : " +  LastWords )
LastWish = input("Warden : Any last wish?\n")
print("Prisoner : " +  LastWish )
print("Warden : Goodbye my friend.")
